name = "codveda-auth"
compatibility_date = "2024-12-01"
pages_build_output_dir = "dist"

[[d1_databases]]
binding = "DB"
database_name = "codveda-db"
database_id = "3861c2d8-7327-4032-81f6-36e91bb0ddad"
